module.exports = [
  {
    date: '2021-01-01',
    name: 'Año nuevo',
    type: 'inamovible',
    weekday: 'viernes',
    nextTo: '3 días no laborables, junto con el sábado 2 y el domingo 3',
  },
  {
    date: '2021-02-15',
    name: 'Feriado de carnaval',
    type: 'inamovible',
    weekday: 'lunes',
    nextTo: '4 días no laborables, junto con el sábado 13, el domingo 14 y el martes 16',
  },
  {
    date: '2021-02-16',
    name: 'Feriado de carnaval',
    type: 'inamovible',
    weekday: 'martes',
    nextTo: '4 días no laborables, junto con el sábado 13, el domingo 14 y el lunes 15',
  },
  {
    date: '2021-03-24',
    name: 'Día Nacional de la Memoria por la Verdad y la Justicia',
    type: 'inamovible',
    weekday: 'miércoles',
  },
  {
    date: '2021-04-02',
    name: 'Día del Veterano y de los Caídos en la Guerra de Malvinas. Coincide con el Viernes Santo',
    type: 'inamovible',
    weekday: 'viernes',
    nextTo: '3 días no laborables, junto con el sábado 3, y el domingo 4',
  },
  {
    date: '2021-05-01',
    name: 'Día del trabajador',
    type: 'inamovible',
    weekday: 'sábado',
  },
  {
    date: '2021-05-24',
    name: 'Feriado con fines turísticos',
    weekday: 'lunes',
    nextTo: '4 días no laborables, junto con el sábado 22, el domingo 23 y el martes 25',
  },
  {
    date: '2021-05-25',
    name: 'Día de la Revolución de Mayo',
    type: 'inamovible',
    weekday: 'martes',
    nextTo: '4 días no laborables, junto con el sábado 22, el domingo 23 y el lunes 24',
  },
  {
    date: '2021-06-20',
    name: 'Paso a la Inmortalidad del Gral. Manuel Belgrano',
    type: 'inamovible',
    weekday: 'domingo',
    nextTo: '3 días no laborables, junto con el sábado 19, y el lunes 21',
  },
  {
    date: '2021-06-21',
    name: 'Paso a la inmortalidad del Gral. Martín Miguel de Güemes',
    movedFrom: '17 de junio',
    type: 'trasladable',
    weekday: 'lunes',
    nextTo: '3 días no laborables, junto con el sábado 19, y el domingo 20',
  },
  {
    date: '2021-07-09',
    name: 'Día de la Independencia',
    type: 'inamovible',
    weekday: 'viernes',
    nextTo: '3 días no laborables, junto con el sábado 10, y el domingo 11',
  },
  {
    date: '2021-08-16',
    name: 'Paso a la inmortalidad del Gral. José de San Martín',
    movedFrom: '17 de agosto',
    type: 'trasladable',
    weekday: 'lunes',
    nextTo: '3 días no laborables, junto con el sábado 14, y el domingo 15',
  },
  {
    date: '2021-10-08',
    name: 'Feriado con fines turísticos',
    weekday: 'viernes',
    nextTo: '4 días no laborables, junto con el sábado 9, el domingo 10 y el lunes 11',
  },
  {
    date: '2021-10-11',
    name: 'Día del Respeto a la Diversidad Cultural',
    movedFrom: '12 de octubre',
    type: 'trasladable',
    weekday: 'lunes',
    nextTo: '4 días no laborables, junto con el viernes 8, el sábado 9 y el domingo 10',
  },
  {
    date: '2021-11-20',
    name: 'Día de la Soberanía Nacional',
    type: 'trasladable',
    weekday: 'sábado',
    nextTo: '3 días no laborables, junto con el domingo 21 y el lunes 22',
  },
  {
    date: '2021-11-22',
    name: 'Feriado con fines turísticos',
    weekday: 'lunes',
    nextTo: '3 días no laborables, junto con el sábado 20 y el domingo 21',
  },
  {
    date: '2021-12-08',
    name: 'Inmaculada Concepción de María',
    type: 'inamovible',
    weekday: 'miércoles',
  },
  {
    date: '2021-12-25',
    name: 'Navidad',
    type: 'inamovible',
    weekday: 'sábado',
  },
];
