service: proxferiadobot
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
functions:
  proxferiadobot:
    handler: handler.proxferiadobot
    events:
      - http:
          path: short-bot
          method: post
          cors: true
